// chrome/options/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

const EXTENSION_URL = "https://chrome.google.com/webstore/detail/click2speech/djfpbemmcokhlllnafdmomgecdlicfhj";

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html'
})
export class ContactComponent implements OnInit {

  readonly REVIEWS_URL = EXTENSION_URL + "/reviews";
  readonly EMAIL = "nagydotzsoltdothunatgmaildotcom".replace(/dot/g, ".").replace(/at/g, "@");    // obfuscate against spammers
  readonly EMAIL_URL = "mailto:" + this.EMAIL + "?subject=click2speech question";

  private backgroundCommunicationPort: chrome.runtime.Port;

  constructor() { }

  ngOnInit() {
    this.backgroundCommunicationPort = chrome.runtime.connect();
  }

  sendAnalytics(interaction: string) {
    this.backgroundCommunicationPort.postMessage({ action: "contactInteraction", interaction });
  }

}

<div class="setting hoverable">
  <div>{{'reviewsUrl' | translate}}</div>
  <a [attr.href]="REVIEWS_URL" target="_blank" (click)="sendAnalytics('reviews-click')">{{REVIEWS_URL}}</a>
</div>
<div class="setting hoverable">
  <div>{{'support' | translate}}</div>
  <a [attr.href]="EMAIL_URL" (click)="sendAnalytics('support-click')">{{EMAIL}}</a>
</div>

// chrome/options/src/components/Contact.tsx
import React from "react";
import translate from "../translate";

const extensionUrl = "https://chrome.google.com/webstore/detail/click2speech/djfpbemmcokhlllnafdmomgecdlicfhj";
const reviewsUrl = extensionUrl + "/reviews";
const email = "nagydotzsoltdothunatgmaildotcom".replace(/dot/g, ".").replace(/at/g, "@");    // obfuscate against spammers
const emailUrl = "mailto:" + email + "?subject=click2speech question";
const reviews = translate('reviews');
const support = translate('support');

const backgroundCommunicationPort = process.env.NODE_ENV !== 'development' ? chrome.runtime.connect() : null;

function sendAnalytics(interaction: string) {
  if(!backgroundCommunicationPort) {
    return; // development env
  }
  backgroundCommunicationPort.postMessage({ action: "contactInteraction", interaction });
}

const Contact = () => (
  <div className="Contact">
    <div className="setting hoverable">
      <div>{reviews}</div>
      <a href={reviewsUrl}
        onClick={e => sendAnalytics('reviews-click')}
        target="_blank"
      >{reviewsUrl}</a>
    </div>
    <div className="setting hoverable">
      <div>{support}</div>
      <a href={emailUrl}
        onClick={e => sendAnalytics('support-click')}
      >{email}</a>
    </div>
  </div>
);

export default Contact as React.FC;
