// chrome/options/app/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent { }

<a routerLink="/general" routerLinkActive="active">
    <span>{{'generalOptionsPage' | translate}}</span>
</a><a routerLink="/speech" routerLinkActive="active">   <!-- 2 as in the same line to remove space between-->
    <span>{{'speechOptionsPage' | translate}}</span>
</a><a id="contactNavButton" routerLink="/contact" routerLinkActive="active">
    <span>{{'contactPage' | translate}}</span>
</a>

// chrome/options/src/components/Navbar.tsx
import React from "react";
import { NavLink } from "react-router-dom";
import "./Navbar.css";
import translate from "../translate";

const general = translate('generalOptionsPage');
const speech = translate('speechOptionsPage');
const contact = translate('contactPage');

// Links in same line to remove space between
const Navbar = () => (
  <div className="Navbar">
    <NavLink to="/general"><span>{general}</span></NavLink>
    <NavLink to="/speech"><span>{speech}</span></NavLink>
    <NavLink to="/contact" id="contactNavButton"><span>{contact}</span></NavLink>
  </div>
);

export default Navbar as React.FC;
